name: Build and push image to GitHub Container Registry
on:
  push:
    branches:
      - prod # aka prod/stable
      - main # aka dev
      
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag for the image, default is dev'
        required: false
        default: 'main'

jobs:
  push-to-container-registry:
    if: github.repository == 'RMCrean/multi-docker-action'  
    name: Build and push data builder Docker image to GitHub Container Registry

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.docker_tag }}" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            echo "tag=prod" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=dev" >> $GITHUB_OUTPUT;
          fi
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./dockerfiles/data.dockerfile
          tags: ghcr.io/rmcrean/swg-data-builder:${{ steps.set-tag.outputs.tag }}
