name: Build and push image to GitHub Container Registry
on:
  push:
    branches:
      - main # push to main gives dev tagged docker image
  
  # Triggered when a release is published
  # Docker image tagged as prod
  release:
      types: [published]
  
  # Triggered manually
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag for the image, default is main'
        required: false
        default: 'main'
      
jobs:
  push-to-container-registry:
    if: github.repository == 'RMCrean/multi-docker-action'  
    name: Build and push Hugo site Docker image to GitHub Container Registry

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.docker_tag }}" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            echo "tag=prod" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=dev" >> $GITHUB_OUTPUT;
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./dockerfiles/hugo.dockerfile
          tags: ghcr.io/rmcrean/swg-hugo-site:${{ steps.set-tag.outputs.tag }}
          build-args: |
            HUGO_ENV_ARG=${
              { github.event_name == 'release' && format('{0},{1}', 'release', github.ref_name) } ||
              { github.ref_name == 'main' && format('{0},{1}', 'development', github.sha) } ||
              { format('{0},{1}', github.ref_name, github.sha) }
            }