name: Playwright Tests
on:
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    
    - name: Build and run the Hugo docker image
      run: | 
        docker build -f dockerfiles/hugo.dockerfile -t hugo-playwright .
        docker run -d -p 8080:8080 --name hugo-container hugo-playwright  

    - name: Run playwright tests
      run: pytest playwright/tests/ --base-url http://localhost:8080 
